version: "3.8"
services:
  api:
    image: lukasveiga/product-warehouse:1.0
    container_name: product-warehouse-api
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: healthcheck
  database:
    image: postgres:14-alpine
    container_name: db-postgresql
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USERNAME}"]
      interval: 3s
      timeout: 5s
      retries: 5
